// for example...

const constants = {
  CREATE_ITEM: 'CREATE_ITEM',
  UPDATE_ITEM: 'EDIT_ITEM',
  DESTROY_ITEM: 'DESTROY_ITEM',
  DESTROY_ALL: 'DESTROY_ALL',
  MANUAL_LOGIN_USER: 'MANUAL_LOGIN_USER',
  LOGIN_SUCCESS_USER: 'LOGIN_SUCCESS_USER',
  LOGIN_ERROR_USER: 'LOGIN_ERROR_USER',
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNUP_SUCCESS_USER: 'SIGNUP_SUCCESS_USER',
  SIGNUP_ERROR_USER: 'SIGNUP_ERROR_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_SUCCESS_USER: 'LOGOUT_SUCCESS_USER',
  LOGOUT_ERROR_USER: 'LOGOUT_ERROR_USER',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_SUCCESS_USER: 'REGISTER_SUCCESS_USER',
  REGISTER_ERROR_USER: 'REGISTER_ERROR_USER',
};

export default constants;
