const constants = {
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  PROTECTED_TEST: 'PROTECTED_TEST',
};

export default constants;
